version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: satcom
      POSTGRES_USER: satcom
      POSTGRES_PASSWORD: satcom
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: {}
